---
- name: Add control host in automationcontroller group
  ansible.builtin.add_host:
    name: "{{ groups['bastions'][0] }}"
    groups: automationcontroller

- name: Install Automation controller
  when: install_automationcontroller | bool
  block:
    - name: Install automation controller from role
      ansible.builtin.include_role:
        name: deploy_automationcontroller

    - name: Clean up
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/automationcontroller_installer"
        - "/tmp/automationcontroller.tar.gz"

    - name: Enable offline automation controller repo
      community.general.ini_file:
        path: "/etc/yum.repos.d/ansible-automation-platform.repo"
        section: ansible-automation-platform
        option: enabled
        value: 1

    - name: Install ansible core & navigator
      ansible.builtin.dnf:
        name:
          - ansible-core
          - ansible-navigator
        state: present

    - name: Include automation configuration loader
      when: configure_automationcontroller | bool
      ansible.builtin.include_role:
        name: automation_platform_loader

    - name: Include cert generator
      when: enable_letsencyrpt_cert | bool
      ansible.builtin.include_role:
        name: aap_controller_cert_issue
