---
- name: Vscode configuration block
  when: install_vscode_server | bool
  block:
    - name: Install vscode server
      ansible.builtin.include_role:
        name: vscode-server

    - name: Clean up
      ansible.builtin.file:
        path: "/tmp/code-server.rpm"
        state: absent

    - name: Insert vscode proxy conf in nginx
      when: install_automationcontroller | bool
      ansible.builtin.blockinfile:
        path: /etc/nginx/conf.d/automation-controller.nginx.conf
        marker: "    # ANSIBLE MANAGED BLOCK"
        insertbefore: '.*location \/ \{.*'
        block: "{{ lookup('file', './files/vscode_nginx.conf') }}"

    - name: Restart nginx
      when: install_automationcontroller | bool
      ansible.builtin.service:
        name: nginx
        state: restarted
