---
- name: Create workshop inventory directories
  ansible.builtin.file:
    path: "/home/{{ student_name }}/lab_inventory/"
    state: directory
    mode: '0755'
    owner: "{{ student_name }}"
    group: "{{ student_name }}"

- name: Generate ansible inventory from template
  ansible.builtin.template:
    src: ./files/hosts_template.j2
    dest: "/home/{{ student_name }}/lab_inventory/hosts"
    mode: '0644'
    owner: "{{ student_name }}"
    group: "{{ student_name }}"

- name: Clone rhel-workshop
  ansible.builtin.git:
    repo: https://github.com/ansible/workshops.git
    dest: /tmp/workshops
    version: devel

- name: Copy rhel-workshop to users home
  ansible.builtin.copy:
    src: "/tmp/workshops/exercises/ansible_windows/"
    dest: "/home/{{ student_name }}/rhel-workshop/"
    remote_src: true
    owner: "{{ student_name }}"
    group: "{{ student_name }}"
    mode: '0644'

- name: Clean workshop clone directory
  ansible.builtin.file:
    path: "/tmp/workshops"
    state: absent

- name: Pull images for student
  become_user: "{{ student_name }}"
  block:
    - name: Pull container images
      containers.podman.podman_image:
        name: "{{ item }}"
        pull: true
        tag: latest
      loop: "{{ ansible_navigator_ee_images }}"
