---
- name: Step 004 software
  hosts: localhost
  gather_facts: false
  become: false
  tags:
    - step004_01
    - software
  tasks:
    - name: Print stage
      ansible.builtin.debug:
        msg: "Software tasks Started"

- name: Configure gitea server
  hosts: gitlab
  become: true
  tasks:
    - name: Inlcude gitea deployment tasks
      ansible.builtin.include_tasks: ./deploy_gitea.yml


- name: Install softwares on bastion
  hosts: bastions
  become: true
  tags:
    - step004_02
    - software
  tasks:
    - name: Include workshop content deployer
      ansible.builtin.include_tasks:
        file: ./setup_ac_and_vscode.yml

    - name: Include workshop content deployer
      ansible.builtin.include_tasks:
        file: ./setup_workshop.yml


- name: Software flight-check
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tags:
    - step004_03
    - software
  tasks:
    - name: Print stage
      ansible.builtin.debug:
        msg: "Software checks completed successfully"
